accelerator: dp
accumulate_grad_batches: 8
amp_backend: apex
amp_level: O2
auto_lr_find: true
auto_scale_batch_size: false
auto_select_gpus: false
automatic_optimization: null
batch_size: 128
benchmark: false
check_val_every_n_epoch: 1
checkpoint_callback: true
default_root_dir: null
deterministic: false
distributed_backend: null
enable_pl_optimizer: true
f: /home/x1112283/.local/share/jupyter/runtime/kernel-41a33db7-14e2-4c79-9148-4a698d979b3e.json
fast_dev_run: false
flush_logs_every_n_steps: 100
gpu_list: 0;1
gpus:
- 0
- 1
gradient_clip_val: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
log_filepath: /home/x1112283/logs_roberta-base_seq_cnv_0.15_1234/performance_log.txt
log_gpu_memory: null
logger: true
lr: 5.0e-05
max_epochs: 100
max_length: 32
max_steps: null
min_epochs: 1
min_steps: null
mlm_probability: 0.15
model_name_or_path: roberta-base
move_metrics_to_cpu: false
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
overfit_batches: 0.0
overwrite_cache: false
plugins: null
precision: 32
prepare_data_per_node: true
process_position: 0
profiler: null
progress_bar_refresh_rate: 1
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
root_dir: /home/x1112283/logs_roberta-base_seq_cnv_0.15_1234
seed: 1234
strategy: dp
sync_batchnorm: false
target: seq_cnv
terminate_on_nan: false
test_file: train_bert_data/test_7days.csv
tpu_cores: !!python/name:pytorch_lightning.utilities.argparse_utils._gpus_arg_default ''
track_grad_norm: -1
train_file: train_bert_data/train_7days.csv
truncated_bptt_steps: null
val_check_interval: 1.0
val_file: train_bert_data/val_7days.csv
warmup_ratio: 0.1
weights_save_path: null
weights_summary: top
workers: 2
